export const friendsQuestions = [
    'Who in this room inspired you the most and why?',
    'What event this year gave the biggest shift in perspective?',
    'Share a story about the most traumatic event you have experienced.',
    'Is there someone in your family that you are worried about and why?',
    'What is a bad habit that you are ashamed of doing and what is prohibiting you from stopping it?',
    'Share the first story that comes to mind when thinking of the person you miss the most presently.',
    'Who hurt you the most and why?',
    'What is the most non-physical pain you felt and how did you overcome it?',
    'What achievement are you the most proud of?',
    'Share the first story that comes to mind of the person sitting next to you.',
    'What is a secret that no one knows?',
    'What chapter would you call this stage of life and why?',
    'What is your biggest fear? if it is something that you could overcome at this very moment, do it.',
    'What is something you would say to your ex?',
    'What relationship caused you to grow the most and how?',
    'What do you find is the most challenging part in growing up?',
    'As you grow older, what do you start to realize about life the most?',
    'Are you happy? Why?',
    'What is something you took for granted and what made you overlook its importance?',
]