export const familyQuestions = [
    'Who made the first move? Mom or Dad?',
    'Share a memorable moment of when you were the age of your child or grandchild.',
    'Have you ever tried drugs? If yes, what kind and at what stage of life did you try it?',
    'Have you given your child the sex talk? If no, why not?',
    'What is something you regret not doing and what stopped you?',
    'What is something about you that your friends know, but your family doesn’t? What’s the reason they don’t know?',
    'Share a story that you kept from telling your parents because you knew you would get in trouble.',
    'What is the biggest lie you told your parents?',
    'Have you ever dated without telling your parents? Why did you keep it from them?',
    'What is the most painful experience you felt that’s not physical?',
    'What’s a trait that your parents have that you admire? Share an instance of when your parents implemented that trait.',
    'We all have challenging periods in our lives - name the most challenging period while raising me/us. How did you overcome it and what did you learn from it?',
    'If you could go back in time, what’s one thing you would change about your childhood?',
    'In your opinion, what is something your child accomplished that you are most proud of and why?',
    'What did you dream of becoming when you were younger?',
    'Is there an event in my life that you can relate to when you were my age?',
    'Which of my friends do you think has the most positive influence on me and which of my frineds do you think have the most negative influnce on me?',
    'What do you think is the most important factor in having a healthy relationship with your family',
]